"""Add hardening: retry tracking, unique version constraint

Revision ID: 17b3dd817110
Revises: aa40470252ee
Create Date: 2026-02-12 17:18:56.208606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b3dd817110'
down_revision: Union[str, Sequence[str], None] = 'aa40470252ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_document_version', 'document_files', ['document_id', 'version'])
    op.add_column('pdf_render_requests', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pdf_render_requests', sa.Column('max_retries', sa.Integer(), nullable=False, server_default='3'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdf_render_requests', 'max_retries')
    op.drop_column('pdf_render_requests', 'retry_count')
    op.drop_constraint('uq_document_version', 'document_files', type_='unique')
    # ### end Alembic commands ###
