"""Restore Asset Standard Fields

Revision ID: 263e901eae2e
Revises: 555a5111d85c
Create Date: 2026-02-17 11:31:52.441650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '263e901eae2e'
down_revision: Union[str, Sequence[str], None] = '555a5111d85c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('serial_number', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('model', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('commissioning_date', sa.Date(), nullable=True))
    op.add_column('assets', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'notes')
    op.drop_column('assets', 'commissioning_date')
    op.drop_column('assets', 'model')
    op.drop_column('assets', 'serial_number')
    # ### end Alembic commands ###
