"""add_year_commissioned_to_tech_specs

Revision ID: 2ce792f69bef
Revises: 8175d4c73182
Create Date: 2026-02-18 19:20:33.798732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce792f69bef'
down_revision: Union[str, Sequence[str], None] = '8175d4c73182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_technical_characteristics', sa.Column('year_commissioned', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_technical_characteristics', 'year_commissioned')
    # ### end Alembic commands ###
