"""Add CTQ Compliance Models

Revision ID: 555a5111d85c
Revises: 6cde83131200
Create Date: 2026-02-17 11:17:00.039359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '555a5111d85c'
down_revision: Union[str, Sequence[str], None] = '6cde83131200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_catalog',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_catalog_code'), 'anomaly_catalog', ['code'], unique=True)
    op.create_table('checklist_categories',
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['checklist_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulatory_text_blocks',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('section_reference', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_text_blocks_code'), 'regulatory_text_blocks', ['code'], unique=True)
    op.create_table('attachments',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('attachment_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_entity_id'), 'attachments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_attachments_tenant_id'), 'attachments', ['tenant_id'], unique=False)
    op.create_table('tenant_agencies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('fax', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_agencies_tenant_id'), 'tenant_agencies', ['tenant_id'], unique=False)
    op.create_table('mission_anomalies',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('catalog_anomaly_id', sa.UUID(), nullable=True),
    sa.Column('custom_code', sa.String(length=50), nullable=True),
    sa.Column('custom_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_anomaly_id'], ['anomaly_catalog.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_anomalies_mission_id'), 'mission_anomalies', ['mission_id'], unique=False)
    op.create_index(op.f('ix_mission_anomalies_tenant_id'), 'mission_anomalies', ['tenant_id'], unique=False)
    op.create_table('mission_attendees',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_attendees_mission_id'), 'mission_attendees', ['mission_id'], unique=False)
    op.create_index(op.f('ix_mission_attendees_tenant_id'), 'mission_attendees', ['tenant_id'], unique=False)
    op.create_table('mission_checklist_results',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('catalog_item_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('investigation_nature', sa.String(length=10), nullable=True),
    sa.Column('observation_code', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['checklist_categories.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_checklist_results_mission_id'), 'mission_checklist_results', ['mission_id'], unique=False)
    op.create_index(op.f('ix_mission_checklist_results_tenant_id'), 'mission_checklist_results', ['tenant_id'], unique=False)
    op.create_table('mission_documents_provided',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('is_provided', sa.Boolean(), nullable=False),
    sa.Column('is_applicable', sa.Boolean(), nullable=False),
    sa.Column('observation_code', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_documents_provided_mission_id'), 'mission_documents_provided', ['mission_id'], unique=False)
    op.create_index(op.f('ix_mission_documents_provided_tenant_id'), 'mission_documents_provided', ['tenant_id'], unique=False)
    op.create_table('mission_previous_controls',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('control_date', sa.Date(), nullable=False),
    sa.Column('control_type', sa.String(length=100), nullable=False),
    sa.Column('technician_name', sa.String(length=255), nullable=True),
    sa.Column('report_number', sa.String(length=100), nullable=True),
    sa.Column('result', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_previous_controls_mission_id'), 'mission_previous_controls', ['mission_id'], unique=False)
    op.create_index(op.f('ix_mission_previous_controls_tenant_id'), 'mission_previous_controls', ['tenant_id'], unique=False)
    op.create_table('mission_work_items',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('deadline_year', sa.Integer(), nullable=True),
    sa.Column('work_description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('observation_code', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_work_items_mission_id'), 'mission_work_items', ['mission_id'], unique=False)
    op.create_index(op.f('ix_mission_work_items_tenant_id'), 'mission_work_items', ['tenant_id'], unique=False)
    op.add_column('assets', sa.Column('installation_number', sa.String(length=50), nullable=True))
    op.add_column('assets', sa.Column('year_commissioned', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('device_type', sa.String(length=50), nullable=True))
    op.add_column('assets', sa.Column('feature_type', sa.String(length=50), nullable=True))
    op.add_column('assets', sa.Column('usage_type', sa.String(length=50), nullable=True))
    op.add_column('assets', sa.Column('load_capacity', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('max_passengers', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('nominal_speed', sa.String(length=50), nullable=True))
    op.add_column('assets', sa.Column('number_of_levels', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('machinery_location', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('maintainer_name', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('maintainer_contract_ref', sa.String(length=100), nullable=True))
    op.drop_column('assets', 'commissioning_date')
    op.drop_column('assets', 'notes')
    op.drop_column('assets', 'serial_number')
    op.drop_column('assets', 'model')
    op.add_column('missions', sa.Column('owner_malveillance_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('missions', sa.Column('stop_request_flag', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('missions', sa.Column('stop_reason', sa.Text(), nullable=True))
    op.add_column('missions', sa.Column('signed_at', sa.DateTime(), nullable=True))
    op.add_column('missions', sa.Column('signed_by_name', sa.String(length=255), nullable=True))
    op.add_column('missions', sa.Column('place_signed', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'place_signed')
    op.drop_column('missions', 'signed_by_name')
    op.drop_column('missions', 'signed_at')
    op.drop_column('missions', 'stop_reason')
    op.drop_column('missions', 'stop_request_flag')
    op.drop_column('missions', 'owner_malveillance_flag')
    op.add_column('assets', sa.Column('model', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('serial_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('commissioning_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('assets', 'maintainer_contract_ref')
    op.drop_column('assets', 'maintainer_name')
    op.drop_column('assets', 'machinery_location')
    op.drop_column('assets', 'number_of_levels')
    op.drop_column('assets', 'nominal_speed')
    op.drop_column('assets', 'max_passengers')
    op.drop_column('assets', 'load_capacity')
    op.drop_column('assets', 'usage_type')
    op.drop_column('assets', 'feature_type')
    op.drop_column('assets', 'device_type')
    op.drop_column('assets', 'year_commissioned')
    op.drop_column('assets', 'installation_number')
    op.drop_index(op.f('ix_mission_work_items_tenant_id'), table_name='mission_work_items')
    op.drop_index(op.f('ix_mission_work_items_mission_id'), table_name='mission_work_items')
    op.drop_table('mission_work_items')
    op.drop_index(op.f('ix_mission_previous_controls_tenant_id'), table_name='mission_previous_controls')
    op.drop_index(op.f('ix_mission_previous_controls_mission_id'), table_name='mission_previous_controls')
    op.drop_table('mission_previous_controls')
    op.drop_index(op.f('ix_mission_documents_provided_tenant_id'), table_name='mission_documents_provided')
    op.drop_index(op.f('ix_mission_documents_provided_mission_id'), table_name='mission_documents_provided')
    op.drop_table('mission_documents_provided')
    op.drop_index(op.f('ix_mission_checklist_results_tenant_id'), table_name='mission_checklist_results')
    op.drop_index(op.f('ix_mission_checklist_results_mission_id'), table_name='mission_checklist_results')
    op.drop_table('mission_checklist_results')
    op.drop_index(op.f('ix_mission_attendees_tenant_id'), table_name='mission_attendees')
    op.drop_index(op.f('ix_mission_attendees_mission_id'), table_name='mission_attendees')
    op.drop_table('mission_attendees')
    op.drop_index(op.f('ix_mission_anomalies_tenant_id'), table_name='mission_anomalies')
    op.drop_index(op.f('ix_mission_anomalies_mission_id'), table_name='mission_anomalies')
    op.drop_table('mission_anomalies')
    op.drop_index(op.f('ix_tenant_agencies_tenant_id'), table_name='tenant_agencies')
    op.drop_table('tenant_agencies')
    op.drop_index(op.f('ix_attachments_tenant_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_entity_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_regulatory_text_blocks_code'), table_name='regulatory_text_blocks')
    op.drop_table('regulatory_text_blocks')
    op.drop_table('checklist_categories')
    op.drop_index(op.f('ix_anomaly_catalog_code'), table_name='anomaly_catalog')
    op.drop_table('anomaly_catalog')
    # ### end Alembic commands ###
