"""add_mission_photo_model

Revision ID: 5824a245bb76
Revises: dc81ade9b1ce
Create Date: 2026-04-15 10:12:33.994436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5824a245bb76'
down_revision: Union[str, Sequence[str], None] = 'dc81ade9b1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission_photos',
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('checklist_result_id', sa.UUID(), nullable=True),
    sa.Column('anomaly_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('captured_at', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['mission_anomalies.id'], ),
    sa.ForeignKeyConstraint(['checklist_result_id'], ['mission_checklist_results.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_photos_tenant_id'), 'mission_photos', ['tenant_id'], unique=False)
    op.alter_column('checklist_categories', 'field_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'BOOL'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checklist_categories', 'field_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'BOOL'::character varying"))
    op.drop_index(op.f('ix_mission_photos_tenant_id'), table_name='mission_photos')
    op.drop_table('mission_photos')
    # ### end Alembic commands ###
