"""add_ctq_ref_models

Revision ID: 5bf7f1136f81
Revises: 263e901eae2e
Create Date: 2026-02-18 19:14:47.869442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf7f1136f81'
down_revision: Union[str, Sequence[str], None] = '263e901eae2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_technical_characteristics',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('load_capacity_kg', sa.Integer(), nullable=True),
    sa.Column('persons_capacity', sa.Integer(), nullable=True),
    sa.Column('nominal_speed_ms', sa.String(length=50), nullable=True),
    sa.Column('travel_height_m', sa.String(length=50), nullable=True),
    sa.Column('stops_count', sa.Integer(), nullable=True),
    sa.Column('machinery_type', sa.String(length=100), nullable=True),
    sa.Column('machinery_location', sa.String(length=255), nullable=True),
    sa.Column('controller_type', sa.String(length=255), nullable=True),
    sa.Column('door_type', sa.String(length=255), nullable=True),
    sa.Column('safety_gear_type', sa.String(length=255), nullable=True),
    sa.Column('last_major_renovation_date', sa.Date(), nullable=True),
    sa.Column('maintenance_contract_ref', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_index(op.f('ix_asset_technical_characteristics_tenant_id'), 'asset_technical_characteristics', ['tenant_id'], unique=False)
    op.add_column('missions', sa.Column('visit_start_datetime', sa.DateTime(), nullable=True))
    op.add_column('missions', sa.Column('visit_end_datetime', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('ape_code', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('legal_mentions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'legal_mentions')
    op.drop_column('tenants', 'ape_code')
    op.drop_column('missions', 'visit_end_datetime')
    op.drop_column('missions', 'visit_start_datetime')
    op.drop_index(op.f('ix_asset_technical_characteristics_tenant_id'), table_name='asset_technical_characteristics')
    op.drop_table('asset_technical_characteristics')
    # ### end Alembic commands ###
