"""add_mission_report_fields

Revision ID: 6cde83131200
Revises: 75a3a4cdb219
Create Date: 2026-02-16 20:35:22.077993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cde83131200'
down_revision: Union[str, Sequence[str], None] = '75a3a4cdb219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('client_reference', sa.String(length=100), nullable=True))
    op.add_column('missions', sa.Column('certification_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'certification_number')
    op.drop_column('missions', 'client_reference')
    # ### end Alembic commands ###
