"""add_tenant_legal_fields

Revision ID: 75a3a4cdb219
Revises: c482fafecafd
Create Date: 2026-02-16 20:34:22.666627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a3a4cdb219'
down_revision: Union[str, Sequence[str], None] = 'c482fafecafd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('region', sa.String(length=100), nullable=True))
    op.add_column('tenants', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('fax', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('siret', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('capital', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('vat_id', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('branding_logo_url', sa.String(length=500), nullable=True))
    op.add_column('tenants', sa.Column('agencies', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'agencies')
    op.drop_column('tenants', 'branding_logo_url')
    op.drop_column('tenants', 'vat_id')
    op.drop_column('tenants', 'capital')
    op.drop_column('tenants', 'siret')
    op.drop_column('tenants', 'website')
    op.drop_column('tenants', 'fax')
    op.drop_column('tenants', 'phone')
    op.drop_column('tenants', 'region')
    op.drop_column('tenants', 'address')
    # ### end Alembic commands ###
