"""add_client_contact_fields

Revision ID: 8175d4c73182
Revises: 5bf7f1136f81
Create Date: 2026-02-18 19:15:39.363466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8175d4c73182'
down_revision: Union[str, Sequence[str], None] = '5bf7f1136f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('legal_form', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('contact_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'contact_name')
    op.drop_column('clients', 'legal_form')
    # ### end Alembic commands ###
