"""add_pdf_tables

Revision ID: aa40470252ee
Revises: 10108bf19829
Create Date: 2026-02-12 16:02:12.915938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa40470252ee'
down_revision: Union[str, Sequence[str], None] = '10108bf19829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_templates',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('engine', sa.Enum('WEASYPRINT', name='pdftemplateengine'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='pdftemplatestatus'), nullable=False),
    sa.Column('template_path', sa.String(length=255), nullable=False),
    sa.Column('style_path', sa.String(length=255), nullable=True),
    sa.Column('assets_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_pdf_template_tenant_code')
    )
    op.create_index(op.f('ix_pdf_templates_tenant_id'), 'pdf_templates', ['tenant_id'], unique=False)
    op.create_table('pdf_render_requests',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', name='pdfrenderstatus'), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('output_document_id', sa.UUID(), nullable=True),
    sa.Column('output_document_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['output_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['output_document_version_id'], ['document_files.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['pdf_templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_render_requests_tenant_id'), 'pdf_render_requests', ['tenant_id'], unique=False)
    
    # Enable RLS
    op.execute("ALTER TABLE pdf_templates ENABLE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY tenant_isolation_policy ON pdf_templates USING (tenant_id = nullif(current_setting('app.current_tenant', true), '')::uuid)")
    
    op.execute("ALTER TABLE pdf_render_requests ENABLE ROW LEVEL SECURITY")
    op.execute("CREATE POLICY tenant_isolation_policy ON pdf_render_requests USING (tenant_id = nullif(current_setting('app.current_tenant', true), '')::uuid)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdf_render_requests_tenant_id'), table_name='pdf_render_requests')
    op.drop_table('pdf_render_requests')
    op.drop_index(op.f('ix_pdf_templates_tenant_id'), table_name='pdf_templates')
    op.drop_table('pdf_templates')
    # ### end Alembic commands ###
