Absence dossier technique comportant l’ensemble des caractéristiques de l’installation.
Absence de la notice d’instruction nécessaire à l’entretien.
Absence de la dernière étude de sécurité prévue par le décret 2008 -1325 du 15 décembre 2008.
Absence du rapport de vérification après transformation ou modification de l’installation.
Absence de Carnet d’entretien prévu à l’article R 125-2-1 du CCH.
Absence de rapport annuel d’activité de l’entreprise en charge de la maintenance.
Absence de plan électrique de l’installation, risque d’une mauvaise identification des différents circuits.
Absence de plan mécanique de l’installation.
Absence de déclaration de conformité « CE » et de dossier technique comportant les caractéristiques de l’installation.