
"use client";

import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue
} from "@/components/ui/select";
import { MissionWorkItem } from "@/types/compliance";
import { complianceService } from "@/services/compliance";
import { Loader2, Plus, Trash2, CalendarClock } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { WORK_ITEM_STATUSES } from "@/constants/elevator-specs";

interface WorkItemsListProps {
    missionId: string;
    items: MissionWorkItem[];
}

export function WorkItemsList({ missionId, items }: WorkItemsListProps) {
    const queryClient = useQueryClient();
    const [newItemDesc, setNewItemDesc] = useState("");
    const [newItemYear, setNewItemYear] = useState<string>("");

    // Update mutation (Full List)
    const updateMutation = useMutation({
        mutationFn: (newItems: MissionWorkItem[]) =>
            complianceService.updateCompliance(missionId, { work_items: newItems }),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ["compliance", missionId] });
            setNewItemDesc("");
            setNewItemYear("");
        }
    });

    const handleAdd = () => {
        if (!newItemDesc) return;

        const newItem: any = { // Using any because ID is generated by backend usually, but here we replace all?
            // Wait, if replace all, we lose IDs of existing items if we don't send them?
            // Backend: "If list is provided, delete existing and recreate."
            // So new IDs will be generated for ALL items unless I keep old ones?
            // But backend implementation: 
            // db.query(MissionWorkItem).delete()
            // for item in payload.work_items: db.add(...)
            // So IDs are ALWAYS regenerated.
            // Ideally I should send everything as "Create" schema without IDs?
            // Or schema allows optional ID?
            // Let's check Schema.
            work_description: newItemDesc,
            deadline_year: newItemYear ? parseInt(newItemYear) : undefined,
            status: "TODO"
        };

        // We need to send ALL items, including existing ones.
        // Since backend regenerates everything, we can just strip IDs from existing items
        // and send them structurally.
        // Warning: StartDate/CreationDate might be lost if not in schema.
        // But for this MVP, it's fine.

        const newPayload = [
            ...items.map(i => ({
                work_description: i.work_description,
                deadline_year: i.deadline_year,
                status: i.status
            })),
            newItem
        ];

        updateMutation.mutate(newPayload as any);
    };

    const handleDelete = (index: number) => {
        const newPayload = items.filter((_, i) => i !== index).map(i => ({
            work_description: i.work_description,
            deadline_year: i.deadline_year,
            status: i.status
        }));
        updateMutation.mutate(newPayload as any);
    };

    const handleStatusChange = (index: number, newStatus: string) => {
        const newPayload = items.map((item, i) => i === index ? { ...item, status: newStatus } : item).map(i => ({
            work_description: i.work_description,
            deadline_year: i.deadline_year,
            status: i.status
        }));
        updateMutation.mutate(newPayload as any);
    };

    return (
        <div className="space-y-4">
            <div className="flex gap-2 items-end border p-4 rounded-md bg-muted/20">
                <div className="grid gap-2 flex-1">
                    <span className="text-sm font-medium">New Work Item</span>
                    <Input
                        placeholder="Review cables, replace battery..."
                        value={newItemDesc}
                        onChange={(e) => setNewItemDesc(e.target.value)}
                    />
                </div>
                <div className="grid gap-2 w-[150px]">
                    <span className="text-sm font-medium">Deadline (Year)</span>
                    <Input
                        type="number"
                        placeholder="2025"
                        value={newItemYear}
                        onChange={(e) => setNewItemYear(e.target.value)}
                    />
                </div>
                <Button onClick={handleAdd} disabled={!newItemDesc || updateMutation.isPending}>
                    {updateMutation.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}
                </Button>
            </div>

            <div className="border rounded-md">
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead>Description</TableHead>
                            <TableHead className="w-[120px]">Échéance</TableHead>
                            <TableHead className="w-[140px]">Statut</TableHead>
                            <TableHead className="w-[80px]"></TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {items.map((item, index) => (
                            <TableRow key={index}>
                                <TableCell>{item.work_description}</TableCell>
                                <TableCell>
                                    {item.deadline_year && (
                                        <div className="flex items-center gap-2 text-muted-foreground">
                                            <CalendarClock className="h-4 w-4" />
                                            {item.deadline_year}
                                        </div>
                                    )}
                                </TableCell>
                                <TableCell>
                                    <Select
                                        value={item.status}
                                        onValueChange={(val) => handleStatusChange(index, val)}
                                    >
                                        <SelectTrigger className="h-8">
                                            <SelectValue />
                                        </SelectTrigger>
                                        <SelectContent>
                                            {WORK_ITEM_STATUSES.map(s => (
                                                <SelectItem key={s.value} value={s.value}>{s.label}</SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                </TableCell>
                                <TableCell>
                                    <Button
                                        variant="ghost"
                                        size="icon"
                                        className="h-8 w-8 text-muted-foreground hover:text-destructive"
                                        onClick={() => handleDelete(index)}
                                    >
                                        <Trash2 className="h-4 w-4" />
                                    </Button>
                                </TableCell>
                            </TableRow>
                        ))}
                        {items.length === 0 && (
                            <TableRow>
                                <TableCell colSpan={4} className="text-center py-8 text-muted-foreground">
                                    Aucun travail planifié.
                                </TableCell>
                            </TableRow>
                        )}
                    </TableBody>
                </Table>
            </div>
        </div>
    );
}
